# Generated by Django 5.1.1 on 2024-09-21 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_topics', to='app.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='topics',
            field=models.ManyToManyField(related_name='categories', to='app.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
