# Generated by Django 5.1.1 on 2024-09-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
