# Generated by Django 5.1.1 on 2024-09-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_topic_category_alter_category_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
