# Generated by Django 5.1.1 on 2024-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_topic_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.TextField(),
        ),
    ]
