# Generated by Django 5.1.1 on 2024-09-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_topic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
    ]
